require:
  - rubocop-minitest


AllCops:
  NewCops: enable

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'test/**/*'

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false
